@extends('layout.admin.master')
@section('title', 'Refunds')
@section('content')
<div class="dashboard-section refunds-page">
    @if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
    @if(session('error'))<div class="alert alert-danger">{{ session('error') }}</div>@endif
    <div class="refunds-hero mb-4"><div><span class="hero-badge"><i class="bi bi-arrow-counterclockwise"></i> Payments recovery</span><h1>Refunds</h1><p>Manage customer refund requests and returned payments.</p></div><a href="{{ route('admin.refunds.create') }}" class="btn btn-light"><i class="bi bi-plus-circle me-2"></i>Add refund</a></div>
    <div class="row g-4 mb-4"><div class="col-12 col-sm-6 col-xl-3"><div class="refund-stat"><span>Total refunds</span><strong>{{ $stats['total'] }}</strong><i class="bi bi-receipt"></i></div></div><div class="col-12 col-sm-6 col-xl-3"><div class="refund-stat stat-orange"><span>Pending</span><strong>{{ $stats['pending'] }}</strong><i class="bi bi-clock-history"></i></div></div><div class="col-12 col-sm-6 col-xl-3"><div class="refund-stat stat-green"><span>Processed</span><strong>{{ $stats['processed'] }}</strong><i class="bi bi-check-circle"></i></div></div><div class="col-12 col-sm-6 col-xl-3"><div class="refund-stat stat-purple"><span>Refunded amount</span><strong>${{ number_format($stats['amount'], 2) }}</strong><i class="bi bi-cash-stack"></i></div></div></div>
    <div class="dashboard-panel refunds-panel"><div class="panel-header refunds-panel-header"><div><span class="eyebrow">Refund directory</span><h5>All refunds</h5><p>Review requests, decisions and processed payments.</p></div></div>
        <form method="GET" class="refund-filters"><div class="refund-search"><i class="bi bi-search"></i><input name="search" value="{{ $search }}" placeholder="Search refund, order or customer..."></div><select name="status" class="form-select"><option value="">All statuses</option>@foreach(['pending','approved','rejected','processed','cancelled'] as $item)<option value="{{ $item }}" @selected($status === $item)>{{ ucfirst($item) }}</option>@endforeach</select><select name="sort" class="form-select"><option value="newest" @selected($sort === 'newest')>Newest</option><option value="oldest" @selected($sort === 'oldest')>Oldest</option><option value="highest" @selected($sort === 'highest')>Highest amount</option><option value="lowest" @selected($sort === 'lowest')>Lowest amount</option></select><button class="btn btn-primary"><i class="bi bi-funnel me-2"></i>Filter</button><a href="{{ route('admin.refunds.index') }}" class="refund-reset">Reset</a></form>
        <div class="table-responsive refunds-table-wrap"><table class="table refunds-table align-middle"><thead><tr><th>Refund</th><th>Order</th><th>Customer</th><th>Amount</th><th>Reason</th><th>Status</th><th>Requested</th><th class="text-end">Action</th></tr></thead><tbody>
        @forelse($refunds as $refund)<tr><td><strong>{{ $refund->refund_number }}</strong></td><td>#{{ $refund->order?->order_number ?? '-' }}</td><td><strong>{{ $refund->user?->name ?? '-' }}</strong><small>{{ $refund->user?->email }}</small></td><td><strong>${{ number_format($refund->amount, 2) }}</strong></td><td><span class="refund-reason">{{ $refund->reason }}</span></td><td><span class="refund-status status-{{ $refund->status }}"><i class="bi bi-circle-fill"></i>{{ ucfirst($refund->status) }}</span></td><td>{{ $refund->requested_at?->format('d M Y') }}</td><td><div class="refund-actions"><a href="{{ route('admin.refunds.show', $refund) }}" class="btn btn-light btn-sm" title="View"><i class="bi bi-eye"></i></a>@if($refund->status !== 'processed')<a href="{{ route('admin.refunds.edit', $refund) }}" class="btn btn-warning btn-sm" title="Edit"><i class="bi bi-pencil"></i></a>@if($refund->status === 'pending')<form method="POST" action="{{ route('admin.refunds.status', $refund) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="approved"><button class="btn btn-success btn-sm" title="Approve"><i class="bi bi-check"></i></button></form><form method="POST" action="{{ route('admin.refunds.status', $refund) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="rejected"><button class="btn btn-danger btn-sm" title="Reject"><i class="bi bi-x"></i></button></form>@elseif($refund->status === 'approved')<form method="POST" action="{{ route('admin.refunds.status', $refund) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="processed"><button class="btn btn-success btn-sm" title="Process"><i class="bi bi-arrow-repeat"></i></button></form>@endif<form method="POST" action="{{ route('admin.refunds.destroy', $refund) }}" class="delete-refund-form">@csrf @method('DELETE')<button class="btn btn-danger btn-sm" title="Delete"><i class="bi bi-trash"></i></button></form>@endif</div></td></tr>@empty<tr><td colspan="8" class="refund-empty"><i class="bi bi-receipt"></i><strong>No refunds found</strong><span>Create a refund request to see it here.</span></td></tr>@endforelse
        </tbody></table></div>@if($refunds->hasPages())<div class="refund-pagination">{{ $refunds->links() }}</div>@endif
    </div>
</div>
@push('js')<script>document.querySelectorAll('.delete-refund-form').forEach(function(form){form.addEventListener('submit',function(e){e.preventDefault();Swal.fire({title:'Delete refund?',text:'Are you sure you want to delete this refund?',icon:'warning',showCancelButton:true,confirmButtonText:'Delete',cancelButtonText:'Cancel',confirmButtonColor:'#dc3545',reverseButtons:true}).then(function(r){if(r.isConfirmed)form.submit();});});});</script>@endpush
@endsection
