@extends('layout.admin.master')
@section('title', 'Refund Details')
@section('content')
<div class="dashboard-section refunds-page">@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif @if(session('error'))<div class="alert alert-danger">{{ session('error') }}</div>@endif
<div class="dashboard-panel refund-detail-hero mb-4"><div><span class="eyebrow">Refund details</span><h2>{{ $refund->refund_number }}</h2><p>{{ $refund->requested_at?->format('d M Y H:i') }}</p></div><div class="refund-detail-actions"><span class="refund-status status-{{ $refund->status }}"><i class="bi bi-circle-fill"></i>{{ ucfirst($refund->status) }}</span><a href="{{ route('admin.refunds.index') }}" class="btn btn-light border">Back</a></div></div>
<div class="row g-4"><div class="col-12 col-xl-8"><div class="dashboard-panel refund-detail-panel"><div class="panel-header"><h5>Refund information</h5></div><div class="refund-detail-grid"><div><small>Amount</small><strong>${{ number_format($refund->amount, 2) }}</strong></div><div><small>Reason</small><strong>{{ $refund->reason }}</strong></div><div><small>Requested at</small><strong>{{ $refund->requested_at?->format('d M Y H:i') }}</strong></div><div><small>Processed at</small><strong>{{ $refund->processed_at?->format('d M Y H:i') ?: '-' }}</strong></div><div class="wide"><small>Note</small><strong>{{ $refund->note ?: '-' }}</strong></div></div></div><div class="dashboard-panel refund-detail-panel mt-4"><div class="panel-header"><h5>Order & customer</h5></div><div class="refund-detail-grid"><div><small>Order</small><strong>#{{ $refund->order?->order_number }}</strong></div><div><small>Order status</small><strong>{{ ucfirst($refund->order?->order_status ?? '-') }}</strong></div><div><small>Customer</small><strong>{{ $refund->user?->name }}</strong></div><div><small>Email</small><strong>{{ $refund->user?->email }}</strong></div><div><small>Phone</small><strong>{{ $refund->order?->phone ?: $refund->user?->phone ?: '-' }}</strong></div></div></div></div><div class="col-12 col-xl-4"><div class="dashboard-panel refund-side-panel"><div class="panel-header"><h5>Payment</h5></div><div class="refund-side-detail"><small>Transaction ID</small><strong>{{ $refund->payment?->transaction_id ?: '-' }}</strong></div><div class="refund-side-detail"><small>Method</small><strong>{{ ucwords(str_replace('_', ' ', $refund->payment?->payment_method ?? '-')) }}</strong></div><div class="refund-side-detail"><small>Payment status</small><strong>{{ ucfirst($refund->payment?->payment_status ?? '-') }}</strong></div><div class="refund-side-detail"><small>Paid at</small><strong>{{ $refund->payment?->paid_at?->format('d M Y H:i') ?: '-' }}</strong></div>@if($refund->status !== 'processed')<a href="{{ route('admin.refunds.edit', $refund) }}" class="btn btn-warning w-100 mt-3"><i class="bi bi-pencil me-2"></i>Edit refund</a>@endif</div></div></div>
@if(in_array($refund->status, ['pending','approved'], true))<div class="dashboard-panel refund-workflow mt-4"><div><span class="eyebrow">Workflow</span><h5>Update refund status</h5></div><div class="refund-workflow-actions">@if($refund->status === 'pending')<form method="POST" action="{{ route('admin.refunds.status', $refund) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="approved"><button class="btn btn-success"><i class="bi bi-check-circle me-2"></i>Approve</button></form><form method="POST" action="{{ route('admin.refunds.status', $refund) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="rejected"><button class="btn btn-danger"><i class="bi bi-x-circle me-2"></i>Reject</button></form>@else<form method="POST" action="{{ route('admin.refunds.status', $refund) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="processed"><button class="btn btn-primary"><i class="bi bi-arrow-repeat me-2"></i>Process refund</button></form>@endif</div></div>@endif
</div>
@endsection
